make doSaveDependingOnFiles nullable again
Kdyby/DoctrineCache pull request #25
Opened 2019-12-03 08:09 UTC by dfx413

addresses #23

2019-12-05 14:43 UTC, Spamercz requested changes
Nullable fix is OK. But class aliases should not be in this. Please remove that so I can merge this.

2019-12-05 14:43 UTC, VBoss commented on src/DI/ClassAliasMap.php
> +	\Kdyby\DoctrineCache\Exception\NotImplementedException::class => \Kdyby\DoctrineCache\Exception\NotImplementedException::class,
This should not be here. You are aliasing same class name. This is here just to provide backwards compatibility for renamed namespaced class `\Kdyby\DoctrineCache\NotImplementedException`

2019-12-05 14:43 UTC, VBoss commented on src/DI/ClassAliasMap.php
> +	\Throwable::class => \Throwable::class,
Same here

2019-12-08 17:22 UTC, dfx413 commented
Hello, sorry for inconvenience. Should be OK now.

2019-12-09 12:05 UTC, Spamercz approved these changes

2019-12-09 12:09 UTC, VBoss commented
No worries :). Merging

2019-12-09 12:09 UTC, merged

2020-08-13 00:42 UTC, greeny commented
Can this be tagged, please?